# ~/.zshrc — D_WM-XFCE
# Light footprint: oh-my-zsh + powerlevel10k + a handful of plugins.

# ----- p10k instant prompt ---------------------------------------------------
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ----- oh-my-zsh -------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    sudo
    history
    extract
    z
    zsh-autosuggestions
    zsh-syntax-highlighting
)

if [ -d "$ZSH" ]; then
    source "$ZSH/oh-my-zsh.sh"
fi

# ----- p10k config (per-user, generated by `p10k configure`) -----------------
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# ----- PATH ------------------------------------------------------------------
typeset -U path PATH
path=(
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "/usr/local/bin"
    $path
)
export PATH

# ----- aliases ---------------------------------------------------------------
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --icons --group-directories-first'
    alias ll='eza -lah --icons --group-directories-first --git'
    alias lt='eza --tree --icons --level=2'
fi
if command -v bat >/dev/null 2>&1; then
    alias cat='bat --paging=never --style=plain'
    alias less='bat --paging=always'
fi
alias ..='cd ..'
alias ...='cd ../..'
alias :q='exit'
alias gst='git status --short --branch'
alias glog='git log --oneline --graph --decorate --all -n 30'

# ----- fastfetch + pokemon on launch (interactive shells only) ---------------
if [[ $- == *i* ]] && [[ -z "$DWM_NO_GREETING" ]]; then
    if command -v fastfetch >/dev/null 2>&1; then
        fastfetch
    fi
    if command -v pokemon-colorscripts >/dev/null 2>&1; then
        pokemon-colorscripts -r --no-title 2>/dev/null
    fi
fi

# ----- editor ----------------------------------------------------------------
export EDITOR="${EDITOR:-vim}"
export VISUAL="$EDITOR"

# ----- history ---------------------------------------------------------------
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$HOME/.zsh_history"
setopt INC_APPEND_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS

# ----- starship fallback if p10k isn't there ---------------------------------
if [ ! -d "${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k" ] && command -v starship >/dev/null 2>&1; then
    eval "$(starship init zsh)"
fi

# ----- archnexus707 first-login tour ----------------------------------------
# Runs the welcome dashboard once. Sentinel: ~/.cache/archnexus/welcomed.
# Re-run with `archnexus-welcome --force`; suppress this turn with NO_WELCOME=1.
if [ -z "${NO_WELCOME:-}" ] && command -v archnexus-welcome >/dev/null 2>&1; then
    archnexus-welcome
fi
