#!/usr/bin/env bash
# polish-archnexus.sh — two minimum-and-cool features for D_WM-XFCE:
#   1. dwm-palette: ImageMagick-driven palette regen from the current wallpaper
#      (rebuilds kitty/rofi/dunst color includes, hot-reloads kitty + dunst).
#   2. dwm-powermenu: rofi -dmenu power menu with Nerd Font glyphs, hover
#      highlight, configurable via $ROFI_POWERMENU_THEME.
#
# Both are wired to i3 keybinds via an idempotent include drop-in so re-running
# the dotfiles phase doesn't undo them.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/safety.sh
. "$SCRIPT_DIR/lib/safety.sh"

apt_pkgs=(
    imagemagick     # convert(1) for palette extraction
    rofi            # already a hard dep; listed to fail loud if it's missing
    dunst           # ditto
)

printf "\n%s ===== archnexus polish (palette + power menu) =====%s\n" "$YELLOW" "$RESET"

apt_install_safe "${apt_pkgs[@]}" || die "polish prerequisites failed (see $DWM_LOG)"

LOCAL_BIN="$HOME/.local/bin"
ROFI_DIR="$HOME/.config/rofi"
I3_DIR="$HOME/.config/i3"
I3_INCLUDE_DIR="$I3_DIR/config.d"
APP_DIR="$HOME/.local/share/applications"

mkdir -p "$LOCAL_BIN" "$ROFI_DIR" "$I3_INCLUDE_DIR" "$APP_DIR" \
    || die "cannot create polish target dirs"

# ----- dwm-palette ----------------------------------------------------------
# Single-shot palette generator. Reads the wallpaper path from $1 or falls back
# to ~/.config/i3/wallpaper.png (the path the i3 wallpaper hook uses). Emits
# colors into ~/.cache/dwm-palette/ then signals kitty + dunst to reload.
PALETTE_BIN="$LOCAL_BIN/dwm-palette"
if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$PALETTE_BIN"
else
    backup_file "$PALETTE_BIN"
    cat > "$PALETTE_BIN" <<'PALETTE_EOF'
#!/usr/bin/env bash
# dwm-palette — regenerate kitty/rofi/dunst colors from a wallpaper.
# Usage: dwm-palette [path-to-wallpaper]   (defaults to ~/.config/i3/wallpaper.png)
set -uo pipefail

WP="${1:-$HOME/.config/i3/wallpaper.png}"
CACHE_DIR="$HOME/.cache/dwm-palette"
mkdir -p "$CACHE_DIR"

if [ ! -f "$WP" ]; then
    printf "[dwm-palette] wallpaper not found: %s\n" "$WP" >&2
    printf "[dwm-palette] hint: drop a wallpaper.png in ~/.config/i3/ first\n" >&2
    exit 1
fi

if ! command -v convert >/dev/null 2>&1; then
    printf "[dwm-palette] ImageMagick 'convert' not found; apt install imagemagick\n" >&2
    exit 1
fi

# Extract 8 dominant colors. Downscale first so the histogram is fast on big
# wallpapers, then -dither None -colors 8 -unique-colors.
mapfile -t COLORS < <(
    convert "$WP" -resize 200x200\! -dither None -colors 8 -unique-colors txt:- \
        2>/dev/null | awk 'NR>1 {print $3}' | sed 's/srgb(.*)//' | head -8
)
if [ "${#COLORS[@]}" -lt 8 ]; then
    printf "[dwm-palette] could only extract %d colors; need 8 — wallpaper too monochrome?\n" "${#COLORS[@]}" >&2
    exit 1
fi

# Write a kitty include
cat > "$CACHE_DIR/kitty.conf" <<KITTY
# generated by dwm-palette $(date -u +%Y-%m-%dT%H:%M:%SZ) from $WP
background    ${COLORS[0]}
foreground    ${COLORS[7]}
color0  ${COLORS[0]}
color1  ${COLORS[1]}
color2  ${COLORS[2]}
color3  ${COLORS[3]}
color4  ${COLORS[4]}
color5  ${COLORS[5]}
color6  ${COLORS[6]}
color7  ${COLORS[7]}
color8  ${COLORS[1]}
color9  ${COLORS[2]}
color10 ${COLORS[3]}
color11 ${COLORS[4]}
color12 ${COLORS[5]}
color13 ${COLORS[6]}
color14 ${COLORS[7]}
color15 ${COLORS[7]}
KITTY

# Write a rofi include (rasi)
cat > "$CACHE_DIR/rofi.rasi" <<ROFI
/* generated by dwm-palette $(date -u +%Y-%m-%dT%H:%M:%SZ) */
* {
    background:     ${COLORS[0]};
    foreground:     ${COLORS[7]};
    selected-bg:    ${COLORS[5]};
    selected-fg:    ${COLORS[0]};
    border-color:   ${COLORS[3]};
}
ROFI

# Write a dunst override (drop the [colors] block into dunst's config)
cat > "$CACHE_DIR/dunst.conf" <<DUNST
# generated by dwm-palette $(date -u +%Y-%m-%dT%H:%M:%SZ)
[urgency_low]
    background = "${COLORS[0]}"
    foreground = "${COLORS[7]}"
    frame_color = "${COLORS[3]}"
[urgency_normal]
    background = "${COLORS[0]}"
    foreground = "${COLORS[7]}"
    frame_color = "${COLORS[5]}"
[urgency_critical]
    background = "${COLORS[0]}"
    foreground = "${COLORS[1]}"
    frame_color = "${COLORS[1]}"
DUNST

# Hot reload — best effort, never fatal
if pidof kitty >/dev/null 2>&1; then
    # kitty re-reads its conf on USR1
    pkill -USR1 kitty 2>/dev/null || true
fi
if command -v dunstctl >/dev/null 2>&1; then
    dunstctl reload 2>/dev/null || pkill -HUP dunst 2>/dev/null || true
elif pidof dunst >/dev/null 2>&1; then
    pkill -HUP dunst 2>/dev/null || true
fi

printf "[dwm-palette] palette updated: bg=%s fg=%s accent=%s\n" \
    "${COLORS[0]}" "${COLORS[7]}" "${COLORS[5]}"
printf "[dwm-palette] add to ~/.config/kitty/kitty.conf:   include %s/kitty.conf\n" "$CACHE_DIR"
printf "[dwm-palette] add to ~/.config/rofi/config.rasi:    @import \"%s/rofi.rasi\"\n" "$CACHE_DIR"
PALETTE_EOF
    chmod +x "$PALETTE_BIN"
    register_undo "rm -f \"$PALETTE_BIN\""
    log "installed dwm-palette to $PALETTE_BIN"
fi

# ----- dwm-powermenu --------------------------------------------------------
POWERMENU_BIN="$LOCAL_BIN/dwm-powermenu"
if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$POWERMENU_BIN"
else
    backup_file "$POWERMENU_BIN"
    cat > "$POWERMENU_BIN" <<'PMENU_EOF'
#!/usr/bin/env bash
# dwm-powermenu — rofi-driven power menu with Nerd Font icons.
# Usage:  dwm-powermenu       (interactive picker)
#         dwm-powermenu lock  (skip picker, run action directly)
set -uo pipefail

THEME="${ROFI_POWERMENU_THEME:-$HOME/.config/rofi/powermenu.rasi}"

declare -A ACTIONS=(
    [Lock]="i3lock -c 000000 2>/dev/null || xset s activate"
    [Logout]="i3-msg exit"
    [Suspend]="systemctl suspend"
    [Hibernate]="systemctl hibernate"
    [Reboot]="systemctl reboot"
    [Shutdown]="systemctl poweroff"
)

# Order + Nerd Font glyphs
ENTRIES=(
    "  Lock"
    "󰍃  Logout"
    "  Suspend"
    "󰒲  Hibernate"
    "  Reboot"
    "  Shutdown"
)

if [ "${1:-}" != "" ]; then
    key="$(printf '%s' "$1" | sed 's/^./\U&/')"
    cmd="${ACTIONS[$key]:-}"
    [ -z "$cmd" ] && { echo "unknown action: $1" >&2; exit 1; }
    eval "$cmd"
    exit $?
fi

pick=$(printf '%s\n' "${ENTRIES[@]}" | \
    rofi -dmenu -i -p "Session" -theme "$THEME" 2>/dev/null) || exit 0
[ -z "$pick" ] && exit 0

# Strip leading glyph + spaces
key=$(printf '%s' "$pick" | sed 's/^[^A-Za-z]*//; s/^ *//')
cmd="${ACTIONS[$key]:-}"
[ -z "$cmd" ] && exit 0

# Confirmation for the destructive ones
case "$key" in
    Shutdown|Reboot|Logout)
        confirm=$(printf 'No\nYes' | rofi -dmenu -i -p "Confirm $key?" -theme "$THEME" 2>/dev/null) || exit 0
        [ "$confirm" = "Yes" ] || exit 0
        ;;
esac

eval "$cmd"
PMENU_EOF
    chmod +x "$POWERMENU_BIN"
    register_undo "rm -f \"$POWERMENU_BIN\""
    log "installed dwm-powermenu to $POWERMENU_BIN"
fi

# ----- rofi power-menu theme ------------------------------------------------
ROFI_THEME="$ROFI_DIR/powermenu.rasi"
if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$ROFI_THEME"
else
    backup_file "$ROFI_THEME"
    cat > "$ROFI_THEME" <<'RASI_EOF'
/* dwm-powermenu rofi theme — cyberpunk, hover highlight, Nerd Font icons */
configuration {
    show-icons: false;
    font: "JetBrainsMono Nerd Font 14";
}

* {
    bg:         #0c0c0c;
    bg-alt:     #161616;
    fg:         #c5c8c6;
    accent:     #00ff9c;
    accent-fg:  #0c0c0c;
    danger:     #ff5577;
    border-c:   #00ff9c;
    background-color: @bg;
    text-color:       @fg;
}

window {
    background-color: @bg;
    border:           2px;
    border-color:     @border-c;
    border-radius:    14px;
    padding:          20px;
    width:            320px;
    location:         center;
    anchor:           center;
}

mainbox  { children: [ inputbar, listview ]; spacing: 16px; }
inputbar { children: [ prompt ]; padding: 6px 12px; background-color: @bg-alt; border-radius: 8px; }
prompt   { text-color: @accent; }

listview {
    columns:        1;
    lines:          6;
    fixed-height:   true;
    scrollbar:      false;
    spacing:        6px;
    cycle:          true;
}

element {
    padding:        10px 14px;
    border-radius:  8px;
    cursor:         pointer;
}

element-text   { text-color: inherit; vertical-align: 0.5; }

element normal.normal      { background-color: @bg-alt;  text-color: @fg; }
element selected.normal    { background-color: @accent;  text-color: @accent-fg; }
element alternate.normal   { background-color: @bg-alt;  text-color: @fg; }
RASI_EOF
    register_undo "rm -f \"$ROFI_THEME\""
    log "installed rofi powermenu theme to $ROFI_THEME"
fi

# ----- i3 include drop-in (keybinds) ----------------------------------------
I3_DROPIN="$I3_INCLUDE_DIR/50-archnexus.conf"
if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$I3_DROPIN"
else
    backup_file "$I3_DROPIN"
    cat > "$I3_DROPIN" <<'I3_EOF'
# archnexus polish keybinds — sourced via `include` from the main i3 config.
# Edit by hand if you want; re-running ./install.sh --only polish replaces this.

# Power menu (top-left button on xfce4-panel also runs this)
bindsym $mod+Escape exec --no-startup-id ~/.local/bin/dwm-powermenu

# Palette regen from current wallpaper
bindsym $mod+Shift+w exec --no-startup-id ~/.local/bin/dwm-palette

# Quick direct actions (skip the picker)
bindsym $mod+Ctrl+l exec --no-startup-id ~/.local/bin/dwm-powermenu Lock
bindsym $mod+Ctrl+r exec --no-startup-id ~/.local/bin/dwm-powermenu Reboot
I3_EOF
    register_undo "rm -f \"$I3_DROPIN\""
    log "installed i3 keybind drop-in to $I3_DROPIN"

    # Ensure the main i3 config sources the include dir. i3 >= 4.21 supports
    # `include` with globs. Append only if not already present.
    I3_MAIN="$I3_DIR/config"
    if [ -f "$I3_MAIN" ] && ! grep -qF "config.d/*.conf" "$I3_MAIN"; then
        backup_file "$I3_MAIN"
        {
            echo ""
            echo "# Added by polish-archnexus.sh — pulls in archnexus keybinds"
            echo "include ~/.config/i3/config.d/*.conf"
        } >> "$I3_MAIN"
        register_undo "sed -i '/Added by polish-archnexus.sh/,+1d' \"$I3_MAIN\""
        log "patched $I3_MAIN to include config.d/*.conf"
    elif [ ! -f "$I3_MAIN" ]; then
        log "i3 main config not yet deployed; the include line will be needed when dotfiles land"
    fi
fi

# ----- xfce4-panel launcher (.desktop) --------------------------------------
DESKTOP_FILE="$APP_DIR/dwm-powermenu.desktop"
if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$DESKTOP_FILE"
else
    backup_file "$DESKTOP_FILE"
    cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Power Menu
Comment=archnexus session menu (lock / logout / suspend / reboot / shutdown)
Exec=$HOME/.local/bin/dwm-powermenu
Icon=system-shutdown
Categories=System;
Terminal=false
EOF
    register_undo "rm -f \"$DESKTOP_FILE\""
    log "installed launcher: $DESKTOP_FILE"
fi

# ----- summary --------------------------------------------------------------
printf "%s archnexus polish complete.\n" "$OK"
printf "%s Keybinds (after i3 reloads):\n" "$INFO"
printf "    SUPER+Escape       — power menu\n"
printf "    SUPER+Shift+W      — regenerate palette from wallpaper\n"
printf "    SUPER+Ctrl+L       — lock directly\n"
printf "    SUPER+Ctrl+R       — reboot directly (confirms)\n"
printf "%s Add the top-left bar icon by right-clicking xfce4-panel → Panel →\n" "$INFO"
printf "    Add New Items… → Launcher → pick 'Power Menu'.\n"
