#!/usr/bin/env bash
# vmware.sh — VMware-guest adaptation for D_WM-XFCE (X11 + picom + i3).
# Early-exits if not running in a VMware guest. Idempotent.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/safety.sh
. "$SCRIPT_DIR/lib/safety.sh"

if ! is_vmware; then
    log "not a VMware guest (systemd-detect-virt = $(systemd-detect-virt 2>/dev/null || echo none)); skipping"
    exit 0
fi

printf "\n%s ===== VMware-guest adaptation =====%s\n" "$YELLOW" "$RESET"

apt_install_safe open-vm-tools open-vm-tools-desktop mesa-utils || die "open-vm-tools / mesa-utils failed (see $DWM_LOG)"

# Enable the userspace daemon (clipboard, dynamic resolution, time sync).
if [ "$DWM_DRY_RUN" != "1" ]; then
    sudo systemctl enable --now open-vm-tools.service >>"$DWM_LOG" 2>&1 || true
    register_undo "sudo systemctl disable --now open-vm-tools.service"
fi

# Probe hardware GL. llvmpipe/softpipe/swrast = software rendering only.
GL_OK=0
if command -v glxinfo >/dev/null 2>&1; then
    if glxinfo 2>/dev/null | grep -qE 'direct rendering: Yes'; then
        renderer=$(glxinfo 2>/dev/null | awk -F': ' '/OpenGL renderer string/ {print $2; exit}')
        case "$renderer" in
            *llvmpipe*|*softpipe*|*swrast*|"")
                log "no hardware GL ($renderer); will disable picom blur"
                ;;
            *)
                log "hardware GL detected: $renderer"
                GL_OK=1
                ;;
        esac
    else
        log "glxinfo: no direct rendering"
    fi
fi

# Write a picom drop-in that the main picom.conf @includes when DWM_VM=1.
PICOM_VM_DROPIN="$HOME/.config/picom/vmware.conf"
mkdir -p "$(dirname "$PICOM_VM_DROPIN")"

if [ "$DWM_DRY_RUN" = "1" ]; then
    printf "%s would write %s\n" "$DRY" "$PICOM_VM_DROPIN"
else
    backup_file "$PICOM_VM_DROPIN"
    {
        echo "# Generated by install-scripts/vmware.sh"
        echo "# VMware-specific picom overrides. Included from picom.conf."
        echo ""
        if [ "$GL_OK" -eq 1 ]; then
            echo "# Hardware GL present — keep blur + animations at modest cost."
            echo "blur-method = \"dual_kawase\";"
            echo "blur-strength = 3;"
            echo "animations = true;"
        else
            echo "# Software rendering only — disable blur, keep cheap animations."
            echo "blur-method = \"none\";"
            echo "blur-background = false;"
            echo "animations = true;"
            echo "animation-stiffness = 200;"
            echo "shadow = false;"
        fi
    } > "$PICOM_VM_DROPIN"
    register_undo "rm -f \"$PICOM_VM_DROPIN\""
    log "wrote $PICOM_VM_DROPIN"
fi

printf "%s VMware adaptation complete. If you later enable 'Accelerate 3D' in\n" "$OK"
printf "%s VMware settings, re-run this script to upgrade to blur+animations.\n" "$INFO"
