#!/bin/bash
# Kali-Hyprland — by archnexus707
# archnexus-keybinds.sh — wire the archnexus-* helper suite into the live
# Hyprland session, and arm the welcome auto-launch on first zsh login.
#
# Idempotent — safe to re-run. Honors a freshly-deployed JaKooLit dotfiles
# tree without clobbering UserKeybinds.conf.
#
# What it does:
#   1. Writes ~/.config/hypr/UserConfigs/archnexus-keybinds.conf with bind=
#      lines for archnexus-power/audio/wifi/bt/clip/cheatsheet/shot/ocr/
#      brightness/volume/nightlight/notify-history/screenrecord.
#   2. Sources that file from ~/.config/hypr/UserConfigs/UserSettings.conf.
#      Because Hyprland uses "last bind wins" semantics, sourcing AFTER any
#      JaKooLit defaults guarantees ours take precedence on collisions.
#   3. Appends an auto-launch snippet to ~/.zshrc so archnexus-welcome runs
#      once on first interactive shell, gated by a sentinel file the
#      welcome script manages itself.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || { echo "[ERROR] cd $PARENT_DIR"; exit 1; }

if ! source "$SCRIPT_DIR/Global_functions.sh"; then
    echo "[ERROR] Failed to source Global_functions.sh"; exit 1
fi

LOG="Install-Logs/install-$(date +%d-%H%M%S)_archnexus-keybinds.log"
mkdir -p "$(dirname "$LOG")"

echo -e "${INFO} ===== archnexus keybinds + welcome wiring ====="

HYPR_USER_CONFIGS="$HOME/.config/hypr/UserConfigs"
KEYBINDS_FILE="$HYPR_USER_CONFIGS/archnexus-keybinds.conf"
SETTINGS_FILE="$HYPR_USER_CONFIGS/UserSettings.conf"
ZSHRC="$HOME/.zshrc"

mkdir -p "$HYPR_USER_CONFIGS" 2>&1 | tee -a "$LOG"

# ----- 1. archnexus-keybinds.conf -------------------------------------------
cat > "$KEYBINDS_FILE" <<'HYPR_EOF'
# archnexus707 keybinds — auto-generated by archnexus-keybinds.sh.
# Source: install-scripts/archnexus-keybinds.sh
# Mirror of the i3 keybinds shipped in D_WM-XFCE so muscle-memory transfers.
#
# Editing this file is fine, but rerunning archnexus-keybinds.sh will
# overwrite it.
#
# IMPORTANT: Hyprland does NOT do "last bind wins" — duplicate bind= entries
# for the same key STACK, and ALL matching dispatchers fire on the keypress.
# So we explicitly `unbind` each key first. Because this file is sourced AFTER
# JaKooLit's UserKeybinds.conf, these unbinds remove their prior binds; the
# bind= lines below then install the archnexus helper as the sole handler.

# ----- clear any colliding JaKooLit defaults before rebinding ---------------
unbind = SUPER,        slash
unbind = SUPER,        H
unbind = SUPER,        X
unbind = SUPER,        W
unbind = SUPER,        A
unbind = SUPER SHIFT,  B
unbind = SUPER,        N
unbind = SUPER,        V
unbind = SUPER SHIFT,  S
unbind = ,             Print
unbind = SUPER,        Print
unbind = SHIFT,        Print
unbind = SUPER SHIFT,  Print
unbind = SUPER SHIFT,  R
unbind = SUPER,        F8
unbind = ,             XF86MonBrightnessUp
unbind = ,             XF86MonBrightnessDown
unbind = ,             XF86AudioRaiseVolume
unbind = ,             XF86AudioLowerVolume
unbind = ,             XF86AudioMute
unbind = ,             XF86AudioPlay
unbind = ,             XF86AudioNext
unbind = ,             XF86AudioPrev

# ----- archnexus pickers ---------------------------------------------------
# Two help bindings — SUPER+slash and SUPER+H — both open archnexus-cheatsheet
# so muscle memory transfers from JaKooLit's Hyprland-Dots convention.
bind = SUPER,        slash,  exec, archnexus-cheatsheet
bind = SUPER,        H,      exec, archnexus-cheatsheet
bind = SUPER,        X,      exec, archnexus-power
bind = SUPER,        W,      exec, archnexus-wifi
bind = SUPER,        A,      exec, archnexus-audio
bind = SUPER SHIFT,  B,      exec, archnexus-bt
bind = SUPER,        N,      exec, archnexus-notify-history
bind = SUPER,        V,      exec, archnexus-clip
bind = SUPER SHIFT,  S,      exec, archnexus-ocr

# ----- screenshots / screen-recording --------------------------------------
# JaKooLit-style convention: SUPER is the modifier verb.
#   Print              full screen
#   SUPER + Print      region (most common — primary screenshot key)
#   SHIFT + Print      region, then open swappy/pinta for annotation
#   SUPER+SHIFT + Print   active window only
bind =        ,      Print,  exec, archnexus-shot screen
bind = SUPER,        Print,  exec, archnexus-shot region
bind = SHIFT,        Print,  exec, archnexus-shot region --edit
bind = SUPER SHIFT,  Print,  exec, archnexus-shot window
bind = SUPER SHIFT,  R,      exec, archnexus-screenrecord toggle

# ----- media + brightness keys (XF86 function keys) ------------------------
bind =        ,  XF86MonBrightnessUp,    exec, archnexus-brightness up
bind =        ,  XF86MonBrightnessDown,  exec, archnexus-brightness down
bind =        ,  XF86AudioRaiseVolume,   exec, archnexus-volume up
bind =        ,  XF86AudioLowerVolume,   exec, archnexus-volume down
bind =        ,  XF86AudioMute,          exec, archnexus-volume mute
bind =        ,  XF86AudioPlay,          exec, playerctl play-pause
bind =        ,  XF86AudioNext,          exec, playerctl next
bind =        ,  XF86AudioPrev,          exec, playerctl previous

# ----- night-light ----------------------------------------------------------
bind = SUPER,  F8,  exec, archnexus-nightlight toggle
HYPR_EOF

echo -e "${OK} Wrote $KEYBINDS_FILE"

# ----- 2. wire keybinds into UserSettings.conf ------------------------------
if [ -f "$SETTINGS_FILE" ]; then
    if ! grep -q "UserConfigs/archnexus-keybinds.conf" "$SETTINGS_FILE"; then
        {
            echo ""
            echo "# Added by archnexus-keybinds.sh — sourced AFTER UserKeybinds.conf"
            echo "# so its leading unbind= lines clear JaKooLit defaults before rebinding."
            echo "source = ~/.config/hypr/UserConfigs/archnexus-keybinds.conf"
        } >> "$SETTINGS_FILE"
        echo -e "${OK} Wired archnexus-keybinds.conf into $SETTINGS_FILE"
    else
        echo -e "${NOTE} archnexus-keybinds.conf already sourced from UserSettings.conf"
    fi
else
    echo -e "${WARN} $SETTINGS_FILE not present yet — dotfiles phase has not run."
    echo -e "${NOTE} Once dotfiles deploy, append manually:"
    echo -e "${NOTE}   source = ~/.config/hypr/UserConfigs/archnexus-keybinds.conf"
fi

# ----- 3. zsh welcome auto-launch ------------------------------------------
if [ -f "$ZSHRC" ]; then
    if ! grep -q 'archnexus-welcome' "$ZSHRC"; then
        cat >> "$ZSHRC" <<'ZSH_EOF'

# ----- archnexus707 first-login tour ----------------------------------------
# Runs the welcome dashboard once. Sentinel: ~/.cache/archnexus/welcomed.
# Re-run with `archnexus-welcome --force`; suppress this turn with NO_WELCOME=1.
if [ -z "${NO_WELCOME:-}" ] && command -v archnexus-welcome >/dev/null 2>&1; then
    archnexus-welcome
fi
ZSH_EOF
        echo -e "${OK} Wired archnexus-welcome auto-launch into $ZSHRC"
    else
        echo -e "${NOTE} archnexus-welcome already wired into $ZSHRC"
    fi
else
    echo -e "${NOTE} $ZSHRC not present — skipping welcome auto-launch."
    echo -e "${NOTE} If you later install zsh, run: archnexus-welcome --force"
fi

echo -e "${OK} archnexus-keybinds.sh complete."
exit 0
