#!/bin/bash
# Kali-Hyprland addition (not present in upstream Debian-Hyprland).
# archnexus polish — two minimum-and-cool features:
#   1. khypr-palette: wallust wrapper that regens the palette from the current
#      swww/hyprpaper wallpaper and reloads kitty + dunst + Hyprland colors.
#   2. wlogout: full-screen power menu (6 icon tiles, hover highlight, ESC closes).
#
# Wires keybinds via a Hyprland drop-in sourced from UserSettings.conf so a
# dotfiles refresh doesn't blow them away.

set -uo pipefail

polish_pkgs=(
  wlogout            # the power menu itself; ships /usr/share/wlogout/icons/*
  imagemagick        # 'convert' used by the palette fallback path
)

## WARNING: DO NOT EDIT BEYOND THIS LINE IF YOU DON'T KNOW WHAT YOU ARE DOING! ##
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || { echo "${ERROR:-[ERROR]} Failed to cd $PARENT_DIR"; exit 1; }

if ! source "$(dirname "$(readlink -f "$0")")/Global_functions.sh"; then
  echo "Failed to source Global_functions.sh"
  exit 1
fi

LOG="Install-Logs/install-$(date +%d-%H%M%S)_polish.log"
mkdir -p "$(dirname "$LOG")"

echo -e "${INFO} ===== archnexus polish (palette + wlogout) ====="

# ----- fastfetch rebrand -----------------------------------------------------
# The Hyprland-Dots deploy their own fastfetch configs that print
# "JaKooLit Version: ${DOTS_VERSION}" in the terminal greeter. Rebrand the
# deployed copies to archnexus707 (idempotent; safe if the files are absent).
FF_DIR="$HOME/.config/fastfetch"
if [ -d "$FF_DIR" ]; then
    for _ff in "$FF_DIR"/*.jsonc; do
        [ -f "$_ff" ] || continue
        sed -i \
            -e 's/JaKooLit Version: \${DOTS_VERSION}/archnexus707/g' \
            -e 's/Jakoolit: v\${DOTS_VERSION}/archnexus707/g' \
            -e 's/JaKooLit/archnexus707/g' \
            -e 's/Jakoolit/archnexus707/g' \
            "$_ff" 2>/dev/null || true
    done
    echo -e "${OK} Rebranded fastfetch greeter configs to archnexus707"
fi

# ----- packages --------------------------------------------------------------
for PKG in "${polish_pkgs[@]}"; do
  install_package "$PKG" "$LOG"
done

# ----- target paths ----------------------------------------------------------
LOCAL_BIN="$HOME/.local/bin"
WLOGOUT_DIR="$HOME/.config/wlogout"
HYPR_USER_CONFIGS="$HOME/.config/hypr/UserConfigs"
WAYBAR_DIR="$HOME/.config/waybar"

mkdir -p "$LOCAL_BIN" "$WLOGOUT_DIR" "$HYPR_USER_CONFIGS" "$WAYBAR_DIR" 2>&1 | tee -a "$LOG"

# ----- khypr-palette ---------------------------------------------------------
PALETTE_BIN="$LOCAL_BIN/khypr-palette"
cat > "$PALETTE_BIN" <<'PALETTE_EOF'
#!/usr/bin/env bash
# khypr-palette — regen color palette from the current wallpaper.
# Prefers `wallust` (installed by the Kali-Hyprland stack); falls back to a
# pure-ImageMagick extraction if wallust isn't on PATH.
# Usage:  khypr-palette                 # auto-detect current swww/hyprpaper wallpaper
#         khypr-palette /path/to/img    # specific wallpaper
set -uo pipefail

current_wallpaper() {
    # swww (preferred — Hyprland default)
    if command -v swww >/dev/null 2>&1; then
        local wp
        wp=$(swww query 2>/dev/null | awk -F'image: ' 'NR==1 {print $2}')
        if [ -n "$wp" ] && [ -f "$wp" ]; then printf '%s' "$wp"; return 0; fi
    fi
    # hyprpaper
    if [ -f "$HOME/.config/hypr/hyprpaper.conf" ]; then
        local wp
        wp=$(awk -F'= ' '/^preload[[:space:]]*=/ {print $2; exit}' "$HOME/.config/hypr/hyprpaper.conf")
        wp="${wp/#\~/$HOME}"
        if [ -n "$wp" ] && [ -f "$wp" ]; then printf '%s' "$wp"; return 0; fi
    fi
    return 1
}

WP="${1:-}"
if [ -z "$WP" ]; then
    WP=$(current_wallpaper) || {
        printf "[khypr-palette] no current wallpaper found (swww/hyprpaper)\n" >&2
        printf "[khypr-palette] usage: khypr-palette /path/to/wallpaper.png\n" >&2
        exit 1
    }
fi
[ -f "$WP" ] || { printf "[khypr-palette] not a file: %s\n" "$WP" >&2; exit 1; }

printf "[khypr-palette] generating palette from %s\n" "$WP"

if command -v wallust >/dev/null 2>&1; then
    wallust run "$WP" 2>&1 || { printf "[khypr-palette] wallust failed\n" >&2; exit 1; }
else
    # Pure-ImageMagick fallback. Writes a minimal kitty include so the terminal
    # at least gets recolored; for full app coverage install wallust.
    command -v convert >/dev/null 2>&1 || {
        printf "[khypr-palette] neither wallust nor ImageMagick is installed\n" >&2
        exit 1
    }
    CACHE="$HOME/.cache/khypr-palette"
    mkdir -p "$CACHE"
    mapfile -t COLORS < <(
        convert "$WP" -resize 200x200\! -dither None -colors 8 -unique-colors txt:- \
            2>/dev/null | awk 'NR>1 {print $3}' | head -8
    )
    [ "${#COLORS[@]}" -ge 8 ] || { printf "[khypr-palette] not enough unique colors in wallpaper\n" >&2; exit 1; }
    {
        printf "# generated by khypr-palette (ImageMagick fallback) %s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf "background %s\nforeground %s\n" "${COLORS[0]}" "${COLORS[7]}"
        for i in 0 1 2 3 4 5 6 7; do printf "color%d %s\n" "$i" "${COLORS[$i]}"; done
        for i in 0 1 2 3 4 5 6 7; do printf "color%d %s\n" "$((i+8))" "${COLORS[$i]}"; done
    } > "$CACHE/kitty.conf"
    printf "[khypr-palette] wrote %s\n" "$CACHE/kitty.conf"
fi

# Reload consumers — best effort
pidof kitty >/dev/null 2>&1 && pkill -USR1 kitty 2>/dev/null || true
command -v dunstctl >/dev/null 2>&1 && dunstctl reload 2>/dev/null || pkill -HUP dunst 2>/dev/null || true
command -v hyprctl >/dev/null 2>&1 && hyprctl reload 2>/dev/null || true

printf "[khypr-palette] done\n"
PALETTE_EOF
chmod +x "$PALETTE_BIN"
echo -e "${OK} Installed $PALETTE_BIN"

# ----- wlogout layout --------------------------------------------------------
# Use the system-shipped SVGs at /usr/share/wlogout/assets/*.svg for icons —
# guaranteed present since `wlogout` was just installed.
WLOGOUT_LAYOUT="$WLOGOUT_DIR/layout"
cat > "$WLOGOUT_LAYOUT" <<'LAYOUT_EOF'
{
    "label" : "lock",
    "action" : "loginctl lock-session",
    "text" : "Lock",
    "keybind" : "l"
}
{
    "label" : "hibernate",
    "action" : "systemctl hibernate",
    "text" : "Hibernate",
    "keybind" : "h"
}
{
    "label" : "logout",
    "action" : "hyprctl dispatch exit 0",
    "text" : "Logout",
    "keybind" : "e"
}
{
    "label" : "shutdown",
    "action" : "systemctl poweroff",
    "text" : "Shutdown",
    "keybind" : "s"
}
{
    "label" : "suspend",
    "action" : "systemctl suspend",
    "text" : "Suspend",
    "keybind" : "u"
}
{
    "label" : "reboot",
    "action" : "systemctl reboot",
    "text" : "Reboot",
    "keybind" : "r"
}
LAYOUT_EOF
echo -e "${OK} Installed $WLOGOUT_LAYOUT"

# ----- wlogout CSS theme -----------------------------------------------------
# Each .button-{label} class on a tile lets us pin the icon SVG. Hover
# scales/brightens and the background-color shifts to the accent.
WLOGOUT_STYLE="$WLOGOUT_DIR/style.css"
cat > "$WLOGOUT_STYLE" <<'CSS_EOF'
/* archnexus wlogout theme — 6 cyberpunk tiles with hover highlight */
* {
    background-image: none;
    box-shadow: none;
    transition: 200ms;
}

window {
    background-color: rgba(12, 12, 12, 0.92);
}

button {
    color: #c5c8c6;
    background-color: #161616;
    border: 2px solid #1f1f1f;
    background-repeat: no-repeat;
    background-position: center;
    background-size: 30%;
    border-radius: 18px;
    margin: 18px;
    font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", monospace;
    font-size: 18px;
    font-weight: 600;
}

button:hover, button:focus, button:active {
    background-color: #00ff9c;
    color: #0c0c0c;
    border-color: #00ff9c;
    outline-style: none;
}

#lock      { background-image: image(url("/usr/share/wlogout/assets/lock.svg"));      }
#logout    { background-image: image(url("/usr/share/wlogout/assets/logout.svg"));    }
#suspend   { background-image: image(url("/usr/share/wlogout/assets/suspend.svg"));   }
#hibernate { background-image: image(url("/usr/share/wlogout/assets/hibernate.svg")); }
#shutdown  { background-image: image(url("/usr/share/wlogout/assets/shutdown.svg"));  }
#reboot    { background-image: image(url("/usr/share/wlogout/assets/reboot.svg"));    }
CSS_EOF
echo -e "${OK} Installed $WLOGOUT_STYLE"

# ----- Hyprland keybind drop-in ---------------------------------------------
POLISH_CONF="$HYPR_USER_CONFIGS/archnexus-polish.conf"
cat > "$POLISH_CONF" <<'HYPR_EOF'
# archnexus polish — power menu + palette regen
# Generated by install-scripts/polish-archnexus.sh; safe to edit by hand.

# SUPER+ESCAPE — full-screen power menu (wlogout)
bind = SUPER, ESCAPE, exec, wlogout -p layer-shell

# SUPER+SHIFT+W — regen palette from current wallpaper
bind = SUPER SHIFT, W, exec, ~/.local/bin/khypr-palette

# Direct actions (skip the menu)
bind = SUPER CTRL, L, exec, loginctl lock-session
bind = SUPER CTRL, R, exec, systemctl reboot
HYPR_EOF
echo -e "${OK} Installed $POLISH_CONF"

# Source the drop-in from UserSettings.conf (idempotent — same pattern vmware.sh uses)
MAIN_USERSETTINGS="$HYPR_USER_CONFIGS/UserSettings.conf"
if [ -f "$MAIN_USERSETTINGS" ]; then
  if ! grep -q "UserConfigs/archnexus-polish.conf" "$MAIN_USERSETTINGS"; then
    {
      echo ""
      echo "# Added by Kali-Hyprland polish phase"
      echo "source = ~/.config/hypr/UserConfigs/archnexus-polish.conf"
    } >> "$MAIN_USERSETTINGS"
    echo -e "${OK} Wired archnexus-polish.conf into $MAIN_USERSETTINGS"
  fi
else
  echo -e "${NOTE} $MAIN_USERSETTINGS not present yet (dotfiles phase hasn't run)."
  echo -e "${NOTE} After dotfiles deploy, add: source = ~/.config/hypr/UserConfigs/archnexus-polish.conf"
fi

# ----- waybar custom module snippet -----------------------------------------
# We don't auto-edit waybar's config.jsonc (its layout is highly user-specific).
# Drop a ready-to-paste module here so the user can wire a top-left tile.
WAYBAR_SNIPPET="$WAYBAR_DIR/archnexus-power.jsonc"
cat > "$WAYBAR_SNIPPET" <<'WAYBAR_EOF'
// Paste this module into your waybar config.jsonc and reference it from
// "modules-left": [...] (or wherever you want the button).
"custom/archnexus-power": {
    "format": "  ",
    "tooltip": true,
    "tooltip-format": "Session",
    "on-click": "wlogout -p layer-shell"
}
WAYBAR_EOF
echo -e "${OK} Waybar module snippet at $WAYBAR_SNIPPET"
echo -e "${INFO} Add it to waybar by inserting the JSON object into your config.jsonc"
echo -e "${INFO}   and adding \"custom/archnexus-power\" to your modules-left array."

# ----- summary --------------------------------------------------------------
echo
echo -e "${OK} archnexus polish complete."
echo -e "${INFO} Keybinds (after Hyprland reload — Mod+Shift+R or rerun login):"
echo -e "    SUPER+Escape       — wlogout power menu (full-screen tiles)"
echo -e "    SUPER+Shift+W      — regen palette from current wallpaper"
echo -e "    SUPER+Ctrl+L       — lock directly"
echo -e "    SUPER+Ctrl+R       — reboot directly"
echo
echo -e "${INFO} Top-left bar icon: paste $WAYBAR_SNIPPET into waybar's config.jsonc"
echo -e "${INFO}   and append \"custom/archnexus-power\" to \"modules-left\"."

printf "\n%.0s" {1..2}
