#!/bin/bash
# Kali-Hyprland addition (not present in upstream Debian-Hyprland).
# VMware-guest tweaks: installs open-vm-tools, probes for working hardware GL
# acceleration, and writes a Hyprland drop-in with whatever fallbacks the probe
# results require.

set -uo pipefail

vmware_pkgs=(
  open-vm-tools
  open-vm-tools-desktop
  mesa-utils
)

## WARNING: DO NOT EDIT BEYOND THIS LINE IF YOU DON'T KNOW WHAT YOU ARE DOING! ##
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || { echo "${ERROR:-[ERROR]} Failed to cd $PARENT_DIR"; exit 1; }

# Source the global functions script (provides install_package, color codes, etc.)
if ! source "$(dirname "$(readlink -f "$0")")/Global_functions.sh"; then
  echo "Failed to source Global_functions.sh"
  exit 1
fi

LOG="Install-Logs/install-$(date +%d-%H%M%S)_vmware.log"

# ----- detect VMware guest ---------------------------------------------------
VIRT="$(systemd-detect-virt 2>/dev/null || echo none)"
if [ "$VIRT" != "vmware" ]; then
  echo -e "${INFO} Not a VMware guest (systemd-detect-virt = $VIRT). Skipping VMware phase."
  exit 0
fi

echo -e "${OK} VMware guest detected. Applying VMware-specific tweaks."

# ----- install open-vm-tools -------------------------------------------------
echo -e "${NOTE} Installing open-vm-tools + open-vm-tools-desktop (Kali stock kernel"
echo -e "       already ships vmwgfx / vmw_balloon modules; this adds the userspace daemons)."
for PKG in "${vmware_pkgs[@]}"; do
  install_package "$PKG" "$LOG"
done

# ----- enable services -------------------------------------------------------
# open-vm-tools provides vmtoolsd.service. Enable it so clipboard sync, dynamic
# resolution, and time sync start at boot. This is fully reversible:
#   sudo systemctl disable --now open-vm-tools.service
sudo systemctl enable --now open-vm-tools.service 2>&1 | tee -a "$LOG" || true

# ----- probe hardware GL -----------------------------------------------------
# In modern VMware Workstation 17+ with "Accelerate 3D graphics" enabled in the
# VM settings, the guest can get hardware OpenGL via vmwgfx + virgl. When that
# is available, Hyprland will work with no fallbacks. When it is NOT available
# (3D accel off, or older VMware/ESXi without GL), we need software rendering
# and to disable expensive effects like blur.

GL_OK=0
if command -v glxinfo >/dev/null 2>&1; then
  if glxinfo 2>/dev/null | grep -qE 'direct rendering: Yes'; then
    # Direct rendering reported. Double-check the renderer string isn't llvmpipe
    renderer=$(glxinfo 2>/dev/null | awk -F': ' '/OpenGL renderer string/ {print $2; exit}')
    case "$renderer" in
      *llvmpipe*|*softpipe*|*"swrast"*)
        echo -e "${WARN} Direct rendering reports yes but software renderer ($renderer); treating as no-accel."
        GL_OK=0
        ;;
      "")
        echo -e "${WARN} Could not read OpenGL renderer string; assuming no acceleration."
        GL_OK=0
        ;;
      *)
        echo -e "${OK} Hardware GL available: $renderer"
        GL_OK=1
        ;;
    esac
  else
    echo -e "${WARN} glxinfo: no direct rendering. Will enable software-rendering fallbacks."
  fi
else
  echo -e "${WARN} glxinfo not found after install; conservatively assuming no GL accel."
fi

# ----- write Hyprland VMware drop-in -----------------------------------------
# archnexus707's Hyprland dotfiles include a UserConfigs/ subtree intended exactly
# for this kind of host-specific override. We drop a file there that the main
# config can `source =` so changes survive dotfile updates.

HYPR_USER_CONFIGS="$HOME/.config/hypr/UserConfigs"
VMWARE_CONF="$HYPR_USER_CONFIGS/vmware.conf"
MAIN_USERSETTINGS="$HYPR_USER_CONFIGS/UserSettings.conf"

mkdir -p "$HYPR_USER_CONFIGS" 2>&1 | tee -a "$LOG"

# Build the drop-in content
{
  echo "# Generated by install-scripts/vmware.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Source of truth for VMware-guest Hyprland overrides."
  echo "# Edit by hand if you want, but re-running install will replace this file"
  echo "# (a backup is taken to ~/.dwm-backup/<ts>/ if you used the safety chassis)."
  echo ""
  echo "# Cursor: hardware cursors crash on vmwgfx with the most common Mesa version."
  echo "env = WLR_NO_HARDWARE_CURSORS,1"
  echo ""
  if [ "$GL_OK" -eq 1 ]; then
    echo "# Hardware GL detected. Keep blur + animations enabled."
    echo "# (no software-rendering env var needed)"
    echo ""
    echo "decoration {"
    echo "    blur {"
    echo "        enabled = true"
    echo "        size = 4"
    echo "        passes = 2"
    echo "        new_optimizations = true"
    echo "    }"
    echo "}"
    echo ""
    echo "animations {"
    echo "    enabled = true"
    echo "    # Keep upstream curves but slightly faster to feel responsive in a VM."
    echo "    bezier = vmEase, 0.16, 1, 0.3, 1"
    echo "    animation = windows, 1, 4, vmEase"
    echo "    animation = workspaces, 1, 4, vmEase, slidefade"
    echo "}"
  else
    echo "# No hardware GL acceleration. Force software rendering and disable blur."
    echo "# Animations stay on at lower complexity so the desktop still feels alive."
    echo "env = WLR_RENDERER_ALLOW_SOFTWARE,1"
    echo ""
    echo "decoration {"
    echo "    blur {"
    echo "        enabled = false"
    echo "    }"
    echo "    drop_shadow = false"
    echo "}"
    echo ""
    echo "animations {"
    echo "    enabled = true"
    echo "    bezier = vmEase, 0.16, 1, 0.3, 1"
    echo "    animation = windows, 1, 3, vmEase"
    echo "    animation = workspaces, 1, 3, vmEase"
    echo "}"
    echo ""
    echo "# Cap explicit-sync expectations on vmwgfx software path."
    echo "render {"
    echo "    explicit_sync = 0"
    echo "    explicit_sync_kms = 0"
    echo "}"
  fi
} > "$VMWARE_CONF"

echo -e "${OK} Wrote VMware drop-in: $VMWARE_CONF"

# Ensure UserSettings.conf sources our file. Append only if not already present.
if [ -f "$MAIN_USERSETTINGS" ]; then
  if ! grep -q "UserConfigs/vmware.conf" "$MAIN_USERSETTINGS"; then
    {
      echo ""
      echo "# Added by Kali-Hyprland VMware phase"
      echo "source = ~/.config/hypr/UserConfigs/vmware.conf"
    } >> "$MAIN_USERSETTINGS"
    echo -e "${OK} Wired vmware.conf into $MAIN_USERSETTINGS"
  fi
else
  echo -e "${NOTE} $MAIN_USERSETTINGS not present yet (dotfiles phase will create it)."
  echo -e "${NOTE} You may need to manually add 'source = ~/.config/hypr/UserConfigs/vmware.conf'"
  echo -e "${NOTE} after dotfiles are deployed."
fi

# ----- summary ---------------------------------------------------------------
echo -e "${OK} VMware phase complete."
echo -e "${INFO} If Hyprland animations look choppy after first login:"
echo -e "       1. enable 'Accelerate 3D graphics' in VMware VM settings"
echo -e "       2. bump VRAM to 256 MB+ in VM settings"
echo -e "       3. re-run: ./install-scripts/vmware.sh"
echo -e "       The probe will pick up hardware GL and re-enable blur automatically."

printf "\n%.0s" {1..2}
